server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=api-gateway

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

management.endpoint.gateway.access=unrestricted
management.endpoints.web.exposure.include=gateway