server.port=8084
spring.application.name=delivery-service

spring.datasource.url=jdbc:postgresql://delivery-db:5432/deliverydb
spring.datasource.username=delivery_service
spring.datasource.password=delivery_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest